### ISSUE TITLE
EIA Question

### ISSUE THREAD

**Issue by jswoboda** [qwsae10/gemini-reu-2021#2]
The EIA example file is calling for a set of equilibrium data sets. Can you provide the config.nml for the equilibrium sim as well? Also you have lp and lq instead of lxp and lyp for the x and y grids, is that because this is magnetic coordinates?

**Comment by qwsae10** [comment]
Sure thing, I added a config.nml for the equilibrium sim. For this one, I used roughly the same conditions as the actual simulation because I was working with an eclipse modded version of GEMINI. Also yes, lp and lq control mag cord grid generation with pygemini.
